[package]
name = "scandir_rs"
version = "2.1.0"
authors = ["Martin Bammer <mrbm74@gmail.com>"]
description = "A fast directory scanner."
edition = "2021"
license = "MIT"
repository = "https://github.com/brmmm3/scandir-rs"
homepage = "https://github.com/brmmm3/scandir-rs"
readme = "../README.md"
keywords = ["fast", "scandir", "walk"]
include = [
    "Cargo.toml",
    "pyproject.toml",
    "src/*",
    "test/*.py",
    "../README.md",
    "../CHANGELOG.md",
    "../LICENSE",
]

[lib]
name = "scandir_rs"
crate-type = ["cdylib"]

[dependencies]
scandir = { path = "../scandir" }

[dependencies.pyo3]
version = "0.17"
features = ["extension-module"]
